# Generated by Django 6.0.5 on 2026-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_country_order_phone_number_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Credit / Debit Card', 'Credit / Debit Card'), ('UPI / NetBanking', 'UPI / NetBanking'), ('Cash on Delivery (COD)', 'Cash on Delivery (COD)')], default='Credit / Debit Card', max_length=50),
        ),
    ]
